src/components/Editor.js

When `keyCommandListeners` lived in the component's state, some key command listeners were never being added to the list of key command listeners. This was due to race conditions caused by React's `setState()` function being asynchronous. Changing the `addKeyCommandListener` to a synchronous function will prevent these race conditions in the future.

Add keyCommandListeners as a property to the Editor

---

src/plugins/createPlugin.js

Fix an unintentional choice to make `Object.assign` calls mutating when accumulating `styleToHTML` and `blockToHTML` options to build an augmented conversion function. When building more than one conversion function with directly conflicting functionality this caused issues with functionality bleeding between converters.

non-mutating Object.assign calls

---

src/components/Editor.js

Fixes issues where `editorState` passed down by context to decorators or other components within the `Editor` tree that don't update enough because [`shouldComponentUpdate` for the editor block component](https://github.com/facebook/draft-js/blob/master/src/component/contents/DraftEditorBlock.react.js#L60-L73) stops any update when changes happen to other blocks.
I think most situations where someone would want to make changes within a decorator would only make changes to data pertaining to that range of text, the associated entity, or the block, but issues arise with applications that autosave when only calling `Entity.mergeData` since it isn't part of the editor state.
I'm open to the idea of switching these to use the [Decorator `props` …

Switch editorState context to be a getEditorState function

---

example/blockStyles.html
example/inlineStyles.html
example/link.html
example/mention.html
example/token.html
package.json
src/plugins/createPlugin.js
src/util/accumulateFunction.js
src/util/blockTypeObjectFunction.js

https://github.com/HubSpot/draft-convert/pull/10 will allow `blockToHTML` to be a function so that block metadata can be inspected. Added the ability when accumulating conversion options in plugins for `blockToHTML` to be either a style object (the old behavior) or a new function that accumulates the same way as others.
I took the opportunity to unify how functions are accumulated across `createPlugin`'s implementation.

Handle blockToHTML function

---

src/components/Editor.js

Adds `getReadOnly` method to `Editor` component child context. Useful for checking the read-only status of the editor in a decorator component, such as a link that should `preventDefault` when being edited but should be triggered when in read-only mode.
Like with `getEditorState` the value is wrapped in a function to avoid any `shouldComponentUpdate`s in blocks preventing updates.

Add getReadOnly method to context of Editor component

---

src/components/Editor.js

Remove 'missing key' warning on OverlayWrapper

Add key prop to OverlayWrapper

---

src/components/Editor.js

Add a `setReadOnly` method to go with `getReadOnly` to allow buttons/decorators/overlays to control the `readOnly` prop going into the editor. The new internal state of readOnly is combined with an OR with the prop passed into `draft-extend`'s `readOnly` prop

setReadOnly

---

src/components/Editor.js
src/style/draft-extend.css

@benbriggs 
- DOM rendering matches visual representation which also fixed `tabIndex` order
- Removed `absolute` positioning, content now manages its own space
- Removed the `li` from the button so that we can have granular control over the child elements (with something like `flexbox`)
- Reduced css selectors that people will have to ⚔  with down the road.
Will break current implementations (probably)…but not that badly. Just if people were depending on the `li` or not including our CSS (because they wanted buttons at the top).  But this will allow for granular control from each supplied button so in the long run, I think it's a win.
- I considered adding a prop that removes buttons below from `tabIndex` but ultimately decided against it for two reasons:
1. Would have to clone each …

switch out order of rendering, refactor css

---

src/components/Editor.js

@benbriggs 
Allow buttons/decorators/overlays to control the `focus` and `blur` of the editor.

Add focus and blur methods to the context

---

README.md
building-plugins.md
example/blockStyles.html
example/inlineStyles.html
example/link.html
example/mention.html
example/token.html
package.json
src/plugins/createPlugin.js
src/util/blockTypeObjectFunction.js
src/util/middlewareAdapter.js

All conversion options to HTML can now be functions that eventually return an empty `ReactElement`, with some other situations where you may want something simpler. I'll go through the possible signatures of each one in order of preference:
- `(next: function) => (block: RawBlock) => (ReactElement | {start: string, end: string})` - Higher-order middleware function that allows for accumulation or transformation on the `ReactElement` generated by other plugins.
-  `(block: RawBlock) => (ReactElement | {start: string, end: string} | void)` - Simpler conversion function that may return a `ReactElement` to be accumulated on, but has no access to `next` to transform any other results. A `{start, end}` object probably isn't a good thing to accumulate on.   Returning `null` or `undefined` will …

Middleware conversion configurations

---

README.md
example/blockStyles.html
example/inlineStyles.html
src/components/Editor.js
src/components/KeyCommandController.js
src/components/Toolbar.js
src/index.js

Also adds a basic `Toolbar` component useful for building Medium-like editor toolbars detached from the `Editor` component. Together with `KeyCommandListener` it can be used to have full control over any key commands coming from the editor. Some notable omissions from things available within the Toolbar context are `focus`, `blur`, `getReadOnly`, and `setReadOnly`. Maybe in the future they could also be moved out of `Editor` but I don't think that makes as much sense as `KeyCommandController`

Separate key command controller and add Toolbar component

---

src/components/KeyCommandController.js

Dynamically added `keyCommandOverrides` should be a higher priority than `keyCommandListeners`.
@benbriggs

keyCommandListeners should have a priority over keyCommandOverrides

---

.babelrc
package.json

`babel-preset-es2015` has been deprecated in favor of babel-reset-env: https://babeljs.io/env/

Switch to babel env

---

package.json

this will quell the console warning:
`npm WARN draft-extend@1.5.1 No license field.`

add license field to package.json

---

package.json
src/components/Editor.js
src/components/KeyCommandController.js
src/components/OverlayWrapper.js
src/components/Toolbar.js
src/plugins/createPlugin.js

Add `prop-types` & `create-react-class` packages to make the minimum amount of changes to be compatible with React 16.

Allow react 16 as peerDependency

---

src/plugins/utils.js

A couple plugin utils were calling `Entity.get` in a couple places - this change should look for `ContentState.getEntity` and use it if available, falling back to the old API if not.

handle draft-js@0.10 Entity API while keeping backwards compatibility

---

README.md
src/components/Editor.js

allows a custom replacement for `CompositeDecorator` to be passed (see 'Beyond CompositeDecorator' section of [this page](https://draftjs.org/docs/advanced-topics-decorators.html#content) for more context on usecases)

add baseDecorator prop defaulting to CompositeDecorator

---

src/components/Editor.js

As of [draft-js#1113](https://github.com/facebook/draft-js/pull/1113/files), `editorState` is now passed to `handleReturn` as a second argument.

fix handleReturn parameters

---

example/tray.html
src/components/Editor.js

**Changes made:**
**Rationale:**
We've built a fairly complex "message composer" component on top of `draft-extend`. The controls section of the `Editor` component contains a toolbar with many plugin buttons. Given the design we're trying to achieve, we need to access the space between the main input and the controls area in order to display validation messages and "stage" yet-to-be-published  file attachment and images.

Add optional renderTray render prop to Editor

---

src/components/Editor.js

Useful when plugins want access to the `Editor` instance for reasons other than calling `focus` or `blur` (e.g. measuring its DOM node).

Expose a ref on the `Editor` via context

---

src/components/Editor.js

I accidentally introduced a propType error in https://github.com/HubSpot/draft-extend/pull/40. This fixes that.

Fix mistyped `editorRef`

---

example/ToolbarButton.js
example/blockStyles.html
example/inlineStyles.html
example/link.html
example/mention.html
example/token.html
example/tray.html
package.json
src/components/Editor.js
src/components/KeyCommandController.js
src/components/OverlayWrapper.js
src/components/Toolbar.js
src/plugins/createPlugin.js
yarn.lock

@maxwellskala @henryqdineen could you take a quick sanity check look at this next week?

remove create-react-class

---

src/plugins/createPlugin.js

cc @maxwellskala 
After doing some digging I found that this memoization was taking a lot of time to process, in fact in some cases significantly more than the regular calculations 🙈 
Memoization is valuable in the accumulation of component options where reference equality is valuable to prevent re-renders, but there's no equivalent situation here to worry about.

Remove unhelpful memoization from conversion option accumulation

---

CHANGELOG.md
package.json
src/components/Editor.js
src/index.js

HubSpot is moving to utilize the updated React context guidelines to allow for React 17 usage. 
This requires us to remove usage of the Legacy context API in favor of the new setup.  A major version bump is included in this, as it will break dependents of the legacy API.
React Context docs here: https://issues.hubspotcentral.com/browse/HMI-10341

Upgrade to React 17 Context API 
